name: Check Commit Message

on: 
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  # push:
  #   branches:
  #     - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.+(Feat|feat|Fix|fix|Design|design|Style|style|Refactor|refactor|Comment|comment|Docs|docs|Test|test|Rename|rename|Remove|remove)*$'
          #pattern: '^?.(Feat|feat|Fix|fix|Design|design|Style)'
          flags: 'gm'
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
          error: 'Your first line has to contain a commit type like  "Fix".'
          
  run-if-fail:
    if: ${{ always() && (needs.check.result=='failure') }}
    needs: [check]
    runs-on: ubuntu-latest
    env: 
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: ${{ env.PR_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '요청해 주신 PR이 COmmit Message을 위반합니다. \n커밋 메시지에 커밋 타입을 포함해 주세요. 
              \n ex) <Fix> : 버그수정
              '
            })
