name: test_licensed

on:
  push: {branches: master}
  pull_request: {branches: master}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run licensed-check
