name: 'coverage report'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            uses: ziishaned/jest-reporter-action@v0.0.1
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              test-command: "yarn jest --coverage"
